language: node_js
node_js:
  - "4.1"
before_install:
  - sudo apt-get update
  - "mkdir -p ~/.npm"
install:
  - sudo apt-get install --force-yes libbluetooth-dev
  - npm install -g node-gyp-install
  - node-gyp-install
  - npm install
env:
  - NODE_ENV=test
